/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Deployment probe; does not load the research archive or run chemistry.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/thermal-1d/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulation Thermal Comparison
         * @description Run predictions from the case; explicitly pair a declared specimen sensor trace.
         */
        post: operations["simulation_thermal_comparison_api_v1_simulations_thermal_1d_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/thermal-1d": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulation Thermal 1D
         * @description Bounded, local, transient conduction; declared properties, no kiln control.
         */
        post: operations["simulation_thermal_1d_api_v1_simulations_thermal_1d_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulation Capabilities
         * @description Validate a generic scenario and report supported outputs only.
         *
         *     This endpoint is intentionally a capability gate. It does not run a kiln,
         *     infer material properties, or return surface/defect probabilities.
         */
        post: operations["simulation_capabilities_api_v1_simulations_capabilities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/chemistry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulation Chemistry
         * @description Calculate deterministic dry-batch chemistry for declared scenario layers.
         *
         *     This is intentionally not a firing or surface simulator. Every recipe row
         *     is resolved from the server's exact local analysis snapshot and research-
         *     only catalogue records are rejected instead of being treated as chemistry.
         */
        post: operations["simulation_chemistry_api_v1_simulations_chemistry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reactions/calcite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calcite Explorer */
        post: operations["calcite_explorer_api_v1_reactions_calcite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/references/openglaze/umf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Openglaze Umf Reference
         * @description Run the optional OpenGlaze CLI as an explicitly external reference.
         *
         *     The route is disabled unless ``OPENGLAZE_REPO_ROOT`` points to a locally
         *     downloaded, license-reviewed checkout. Its result never replaces the
         *     deterministic Ceramic Material Intelligence chemistry report.
         */
        post: operations["openglaze_umf_reference_api_v1_references_openglaze_umf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/references/openglaze/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare With Openglaze
         * @description Compare our exact local chemistry snapshot with OpenGlaze.
         *
         *     This endpoint is a reproducibility aid, not a consensus engine. It only
         *     compares UMF-equivalent fields and preserves the external report and
         *     material-name limitations separately.
         */
        post: operations["compare_with_openglaze_api_v1_references_openglaze_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/references/openglaze/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay Openglaze Comparison
         * @description Verify a downloaded comparison snapshot without rerunning OpenGlaze.
         *
         *     This endpoint checks the stored comparison arithmetic and input hash. It
         *     intentionally does not fetch or execute the historical external source.
         */
        post: operations["replay_openglaze_comparison_api_v1_references_openglaze_replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/references/openglaze/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Openglaze Comparison
         * @description Persist one immutable comparison snapshot in the local archive.
         */
        post: operations["save_openglaze_comparison_api_v1_references_openglaze_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/references/openglaze/runs/{comparison_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Openglaze Comparison
         * @description Load one archived comparison and verify its checksum before returning it.
         */
        get: operations["get_openglaze_comparison_api_v1_references_openglaze_runs__comparison_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validation/temperature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Temperature Comparison */
        post: operations["temperature_comparison_api_v1_validation_temperature_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outcomes/assess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Outcome Indicators */
        post: operations["outcome_indicators_api_v1_outcomes_assess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validation/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Observed Outcomes
         * @description Link measured/reported specimen observations to a calculated report.
         */
        post: operations["validate_observed_outcomes_api_v1_validation_outcomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Experiment Record
         * @description Create or reuse an immutable experiment/specimen context record.
         */
        post: operations["create_experiment_record_api_v1_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Experiment Record
         * @description Load one immutable experiment/specimen context record.
         */
        get: operations["get_experiment_record_api_v1_experiments__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{record_id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Experiment Observations
         * @description List checksum-verified observations linked to an experiment record.
         */
        get: operations["get_experiment_observations_api_v1_experiments__record_id__observations_get"];
        put?: never;
        /**
         * Create Experiment Observation
         * @description Store one immutable observation linked to an existing experiment record.
         */
        post: operations["create_experiment_observation_api_v1_experiments__record_id__observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{record_id}/measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Experiment Measurements
         * @description List checksum-verified empirical measurements for a real specimen record.
         */
        get: operations["get_experiment_measurements_api_v1_experiments__record_id__measurements_get"];
        put?: never;
        /**
         * Create Experiment Measurement
         * @description Archive one empirical specimen measurement; no prediction is produced.
         */
        post: operations["create_experiment_measurement_api_v1_experiments__record_id__measurements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validation/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Validation Run
         * @description Persist one immutable observed/calculated validation report locally.
         */
        post: operations["save_validation_run_api_v1_validation_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validation/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Validation Run
         * @description Load one immutable validation report after checksum verification.
         */
        get: operations["get_validation_run_api_v1_validation_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Materials */
        get: operations["materials_api_v1_materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library */
        get: operations["library_api_v1_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/material-analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Material Analysis
         * @description Return one exact local analysis record with provenance and eligibility.
         */
        get: operations["material_analysis_api_v1_material_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/archive/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research Archive Recipes */
        get: operations["research_archive_recipes_api_v1_research_archive_recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/archive/recipes/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research Archive Recipe */
        get: operations["research_archive_recipe_api_v1_research_archive_recipes__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisReport */
        AnalysisReport: {
            /**
             * Schema Version
             * @default prototype-report/1
             * @constant
             */
            schema_version: "prototype-report/1";
            /** Report Id */
            report_id: string;
            request: components["schemas"]["AnalysisRequest"];
            chemistry: components["schemas"]["ChemistryResult"];
            process: components["schemas"]["ProcessReport"];
            /** Materials */
            materials: components["schemas"]["Material"][];
            /** Notices */
            notices: string[];
            /**
             * Persistence
             * @default NOT_STORED_EXPORT_TO_KEEP
             * @constant
             */
            persistence: "NOT_STORED_EXPORT_TO_KEEP";
        };
        /** AnalysisRequest */
        AnalysisRequest: {
            /** Recipe Name */
            recipe_name: string;
            /** Ingredients */
            ingredients: components["schemas"]["Ingredient"][];
            /**
             * Base Mass G
             * @default 100
             */
            base_mass_g: number;
            context?: components["schemas"]["FiringContext"];
        };
        /** Catalogue */
        Catalogue: {
            /** Materials */
            materials: components["schemas"]["Material"][];
            example: components["schemas"]["AnalysisRequest"];
            /** Notice */
            notice: string;
        };
        /** ChemistryComparisonRequest */
        ChemistryComparisonRequest: {
            /** Ingredients */
            ingredients: components["schemas"]["Ingredient"][];
            /**
             * Base Mass G
             * @default 100
             */
            base_mass_g: number;
            /** Cone */
            cone: number;
            /** External Names */
            external_names?: {
                [key: string]: string;
            };
        };
        /** ChemistryResult */
        ChemistryResult: {
            /** Schema Version */
            schema_version: string;
            /** Engine Version */
            engine_version: string;
            /**
             * Evidence Kind
             * @constant
             */
            evidence_kind: "CALCULATED";
            /**
             * Method Kind
             * @constant
             */
            method_kind: "DETERMINISTIC";
            /** Qualifier */
            qualifier: string;
            /** Input Snapshot */
            input_snapshot: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Constant Set Id */
            constant_set_id: string;
            /** Constant Set Sha256 */
            constant_set_sha256: string;
            /** Umf Convention */
            umf_convention: string;
            /** Input Hash */
            input_hash: string;
            /** Normalized Ingredients */
            normalized_ingredients: components["schemas"]["NormalizedIngredient"][];
            /** Oxide Mass G */
            oxide_mass_g: {
                [key: string]: number;
            };
            /** Oxide Moles */
            oxide_moles: {
                [key: string]: number;
            };
            /** Oxide Mol Pct */
            oxide_mol_pct: {
                [key: string]: number;
            };
            /** Retained Oxide Wt Pct */
            retained_oxide_wt_pct: {
                [key: string]: number;
            };
            /** Loi Mass G */
            loi_mass_g: number;
            /** Retained Oxide Mass G */
            retained_oxide_mass_g: number;
            /** Total Dry Batch Mass G */
            total_dry_batch_mass_g: number;
            umf: components["schemas"]["UMF"];
            /** Flux Distribution */
            flux_distribution: {
                [key: string]: number;
            } | null;
            /** Ratios */
            ratios: {
                [key: string]: components["schemas"]["Ratio"];
            };
            /** Warnings */
            warnings: string[];
            predictions: components["schemas"]["Predictions"];
        };
        /**
         * ComparisonReplayRequest
         * @description Previously exported comparison snapshot to verify arithmetically.
         */
        ComparisonReplayRequest: {
            /** Snapshot */
            snapshot: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** ComparisonRequest */
        ComparisonRequest: {
            /** Prediction */
            prediction: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Observation */
            observation: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** ErrorItem */
        ErrorItem: {
            /** Code */
            code: string;
            /** Path */
            path: string[];
            /** Message */
            message: string;
            /**
             * Severity
             * @default ERROR
             * @constant
             */
            severity: "ERROR";
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Errors */
            errors: components["schemas"]["ErrorItem"][];
        };
        /** ExperimentRecordContext */
        ExperimentRecordContext: {
            /**
             * Body Revision
             * @default
             */
            body_revision: string;
            /**
             * Glaze Revision
             * @default
             */
            glaze_revision: string;
            /**
             * Application Revision
             * @default
             */
            application_revision: string;
            /**
             * Firing Run Id
             * @default
             */
            firing_run_id: string;
        };
        /** ExperimentRecordRequest */
        ExperimentRecordRequest: {
            /** Experiment Id */
            experiment_id: string;
            /** Specimen Id */
            specimen_id: string;
            /**
             * Record Kind
             * @default REAL
             * @enum {string}
             */
            record_kind: "REAL" | "SYNTHETIC";
            /**
             * Question
             * @default
             */
            question: string;
            /** Source Ref */
            source_ref: string;
            context?: components["schemas"]["ExperimentRecordContext"];
            /** Analysis Report Id */
            analysis_report_id?: string | null;
            /** Chemistry Input Hash */
            chemistry_input_hash?: string | null;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** ExperimentValidationArchiveRequest */
        ExperimentValidationArchiveRequest: {
            /** Report */
            report: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** ExperimentValidationRequest */
        ExperimentValidationRequest: {
            /** Experiment Id */
            experiment_id: string;
            context: components["schemas"]["ValidationContext"];
            /** Calculated Report */
            calculated_report: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Observations */
            observations: components["schemas"]["ObservedOutcome"][];
        };
        /** ExternalReferenceIngredient */
        ExternalReferenceIngredient: {
            /** Name */
            name: string;
            /** Amount */
            amount: number;
        };
        /** FiringContext */
        FiringContext: {
            /**
             * Cone
             * @default UNKNOWN
             * @enum {string}
             */
            cone: "UNKNOWN" | "06" | "04" | "6" | "8" | "10";
            /** Temperature C */
            temperature_c?: number | null;
            /**
             * Atmosphere
             * @default UNKNOWN
             * @enum {string}
             */
            atmosphere: "UNKNOWN" | "OXIDATION" | "REDUCTION" | "OTHER";
            /**
             * Clay Body
             * @default
             */
            clay_body: string;
            body_window?: components["schemas"]["ReportedWindow"] | null;
            glaze_window?: components["schemas"]["ReportedWindow"] | null;
            schedule?: components["schemas"]["FiringSchedule"] | null;
        };
        /** FiringSchedule */
        FiringSchedule: {
            /** Start C */
            start_c: number;
            /** Segments */
            segments: components["schemas"]["FiringSegment"][];
        };
        /** FiringSegment */
        FiringSegment: {
            /** Target C */
            target_c: number;
            /** Rate C Per Hour */
            rate_c_per_hour: number | null;
            /**
             * Hold Minutes
             * @default 0
             */
            hold_minutes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Ingredient */
        Ingredient: {
            /** Analysis Id */
            analysis_id: string;
            /** Amount */
            amount: number;
            /**
             * Role
             * @default BASE
             * @enum {string}
             */
            role: "BASE" | "ADDITION";
        };
        JsonValue: unknown;
        /** KilnThermalComparisonRequest */
        KilnThermalComparisonRequest: {
            /** Experiment */
            experiment: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** KilnThermalRequest */
        KilnThermalRequest: {
            /** Case */
            case: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** LabMeasurementArchiveResponse */
        LabMeasurementArchiveResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "CREATED" | "EXISTS" | "AVAILABLE";
            /** Measurement Id */
            measurement_id: string;
            /** Measurement Sha256 */
            measurement_sha256: string;
            measurement: components["schemas"]["LabMeasurementSnapshot"];
        };
        /**
         * LabMeasurementRequest
         * @description Empirical record; this endpoint does not calculate or predict its value.
         */
        LabMeasurementRequest: {
            /**
             * Observable
             * @enum {string}
             */
            observable: "drying_linear_shrinkage_pct" | "firing_linear_shrinkage_pct" | "glaze_runout_distance_mm" | "water_absorption_mass_pct" | "gloss_mean_gu" | "glaze_surface_class" | "optical_transmission_class" | "glaze_adhesion_assessment" | "defect_observation";
            /** Value */
            value?: number | string | null;
            /** Unit */
            unit?: string | null;
            /** Specimen Id */
            specimen_id: string;
            /** Source Ref */
            source_ref: string;
            /** Method */
            method: string;
            /**
             * Status
             * @enum {string}
             */
            status: "MEASURED" | "REPORTED" | "OBSERVED" | "OBSERVED_PRESENT" | "OBSERVED_ABSENT" | "NOT_ASSESSED" | "REPORTED_PRESENT" | "REPORTED_ABSENT";
            /** Uncertainty */
            uncertainty?: number | null;
            /** Uncertainty Kind */
            uncertainty_kind?: ("STANDARD_UNCERTAINTY" | "EXPANDED_UNCERTAINTY" | "REPEAT_SD" | "INSTRUMENT_RESOLUTION" | "REPORTED_UNSPECIFIED") | null;
            /** Replicate Id */
            replicate_id?: string | null;
            /** Conditions */
            conditions?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** LabMeasurementSnapshot */
        LabMeasurementSnapshot: {
            /**
             * Schema Version
             * @constant
             */
            schema_version: "lab-measurement-v1";
            /** Engine Version */
            engine_version: string;
            /**
             * Evidence Kind
             * @constant
             */
            evidence_kind: "OBSERVED";
            /**
             * Method Kind
             * @constant
             */
            method_kind: "EMPIRICAL";
            /** Record Id */
            record_id: string;
            /** Measurement Id */
            measurement_id: string;
            measurement: components["schemas"]["LabMeasurementRequest"];
        };
        /** Material */
        Material: {
            /** Analysis Id */
            analysis_id: string;
            /** Name */
            name: string;
            /** Formula */
            formula: string;
            /** Version */
            version: string;
            /** Qualifier */
            qualifier: string;
            /** Basis */
            basis: string;
            /** Loi Pct */
            loi_pct: number;
            /** Oxides */
            oxides: {
                [key: string]: number;
            };
            /** Source Ref */
            source_ref: string;
            /** Source Url */
            source_url: string;
        };
        /** NormalizedIngredient */
        NormalizedIngredient: {
            /** Analysis Id */
            analysis_id: string;
            /** Amount */
            amount: number;
            /**
             * Role
             * @default BASE
             * @enum {string}
             */
            role: "BASE" | "ADDITION";
            /** Original Amount */
            original_amount: number;
            /** Percent Of Base */
            percent_of_base: number;
            /** Dry Mass G */
            dry_mass_g: number;
        };
        /** ObservedOutcome */
        ObservedOutcome: {
            /**
             * Observable
             * @enum {string}
             */
            observable: "gloss_mean_gu" | "water_absorption_mass_pct" | "apparent_open_porosity_volume_pct";
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /** Specimen Id */
            specimen_id: string;
            /** Source Ref */
            source_ref: string;
            /** Method */
            method: string;
            /**
             * Status
             * @enum {string}
             */
            status: "MEASURED" | "REPORTED";
        };
        /** OpenGlazeReferenceRequest */
        OpenGlazeReferenceRequest: {
            /** Ingredients */
            ingredients: components["schemas"]["ExternalReferenceIngredient"][];
            /** Cone */
            cone: number;
        };
        /** OutcomeRequest */
        OutcomeRequest: {
            /** Fit */
            fit?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Flow */
            flow?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Wetting */
            wetting?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Porosity */
            porosity?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Gloss */
            gloss?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
        };
        /** Predictions */
        Predictions: {
            /**
             * Status
             * @constant
             */
            status: "UNAVAILABLE";
            /** Reason */
            reason: string;
        };
        /** ProcessReport */
        ProcessReport: {
            /** Engine Version */
            engine_version: string;
            /** Input Hash */
            input_hash: string;
            /** Input Snapshot */
            input_snapshot: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Status
             * @constant
             */
            status: "PARTIAL";
            /**
             * Checks Evidence Kind
             * @constant
             */
            checks_evidence_kind: "CALCULATED";
            /**
             * Checks Method Kind
             * @constant
             */
            checks_method_kind: "DETERMINISTIC";
            /** Checks Qualifier */
            checks_qualifier: string;
            body_window: components["schemas"]["WindowCheck"];
            glaze_window: components["schemas"]["WindowCheck"];
            schedule: components["schemas"]["ScheduleCheck"];
            /** Stages */
            stages: components["schemas"]["ProcessStage"][];
            /** Warnings */
            warnings: string[];
            /** Limitations */
            limitations: string[];
        };
        /** ProcessStage */
        ProcessStage: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @constant
             */
            status: "UNAVAILABLE";
            /**
             * Evidence Kind
             * @constant
             */
            evidence_kind: "PREDICTED";
            /** Probability */
            probability: null;
            /** Reason */
            reason: string;
            /** Required Evidence */
            required_evidence: string[];
            /** Next Step */
            next_step: string;
        };
        /** Ratio */
        Ratio: {
            /**
             * Status
             * @enum {string}
             */
            status: "AVAILABLE" | "UNAVAILABLE";
            /** Unavailable Reason */
            unavailable_reason: string | null;
            /** Value */
            value: number | null;
        };
        /** ReactionExplorerRequest */
        ReactionExplorerRequest: {
            /** Mass G */
            mass_g: number;
            /** Conversion */
            conversion: number;
        };
        /** ReportedWindow */
        ReportedWindow: {
            /** Product Id */
            product_id: string;
            /** Source Ref */
            source_ref: string;
            /** Conditions */
            conditions: string;
            /** Min C */
            min_c: number;
            /** Max C */
            max_c: number;
        };
        /** ScenarioRecipeIngredient */
        ScenarioRecipeIngredient: {
            /** Analysis Id */
            analysis_id: string;
            /** Amount */
            amount: number;
            /**
             * Role
             * @enum {string}
             */
            role: "BASE" | "ADDITION";
        };
        /** ScenarioRecipeLayer */
        ScenarioRecipeLayer: {
            /** Layer Id */
            layer_id: string;
            /**
             * Base Mass G
             * @default 100
             */
            base_mass_g: number;
            /** Ingredients */
            ingredients: components["schemas"]["ScenarioRecipeIngredient"][];
        };
        /** ScheduleCheck */
        ScheduleCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "AVAILABLE" | "PARTIAL" | "UNAVAILABLE";
            /** Known Duration Minutes */
            known_duration_minutes: number | null;
            /** Total Duration Minutes */
            total_duration_minutes: number | null;
            /** Peak C */
            peak_c: number | null;
            /** Code */
            code: string;
        };
        /** SimulationChemistryRequest */
        SimulationChemistryRequest: {
            scenario: components["schemas"]["SimulationScenarioRequest"];
            /** Recipes */
            recipes: components["schemas"]["ScenarioRecipeLayer"][];
        };
        /** SimulationFiringSchedule */
        SimulationFiringSchedule: {
            /** Name */
            name: string;
            /** Start C */
            start_c: number;
            /** Segments */
            segments: components["schemas"]["SimulationFiringSegment"][];
            /**
             * Atmosphere
             * @default UNKNOWN
             */
            atmosphere: string;
        };
        /** SimulationFiringSegment */
        SimulationFiringSegment: {
            /** Target C */
            target_c: number;
            /** Rate C Per Hour */
            rate_c_per_hour?: number | null;
            /**
             * Hold Minutes
             * @default 0
             */
            hold_minutes: number;
        };
        /** SimulationGeometry */
        SimulationGeometry: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "TILE" | "PLATE" | "CYLINDER" | "SPHERE" | "CUSTOM";
            /** Thickness Mm */
            thickness_mm: number;
            /** Length Mm */
            length_mm?: number | null;
            /** Width Mm */
            width_mm?: number | null;
            /** Diameter Mm */
            diameter_mm?: number | null;
        };
        /** SimulationLayer */
        SimulationLayer: {
            /** Layer Id */
            layer_id: string;
            /** Materials */
            materials: components["schemas"]["SimulationMaterialRef"][];
            /**
             * Application Method
             * @default NONE
             * @enum {string}
             */
            application_method: "NONE" | "DIP" | "BRUSH" | "SPRAY" | "POUR" | "SCREEN" | "OTHER";
            /**
             * Coat Count
             * @default 0
             */
            coat_count: number;
            /** Dry Thickness Um */
            dry_thickness_um?: number | null;
            /** Wet Thickness Um */
            wet_thickness_um?: number | null;
            /** Drying Minutes */
            drying_minutes?: number | null;
        };
        /** SimulationMaterialRef */
        SimulationMaterialRef: {
            /** Analysis Id */
            analysis_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "BODY" | "ENGOBE" | "GLAZE" | "ADDITION" | "OVERGLAZE";
            /** Amount G */
            amount_g?: number | null;
            /** Layer Id */
            layer_id?: string | null;
        };
        /** SimulationScenarioRequest */
        SimulationScenarioRequest: {
            /** Scenario Id */
            scenario_id: string;
            body: components["schemas"]["SimulationLayer"];
            /** Layers */
            layers?: components["schemas"]["SimulationLayer"][];
            bisque?: components["schemas"]["SimulationFiringSchedule"] | null;
            final_firing: components["schemas"]["SimulationFiringSchedule"];
            geometry: components["schemas"]["SimulationGeometry"];
            target: components["schemas"]["SimulationTarget"];
            /** Metadata */
            metadata?: {
                [key: string]: string;
            };
        };
        /** SimulationTarget */
        SimulationTarget: {
            /** Objective */
            objective: string;
            /** Requested Outputs */
            requested_outputs?: string[];
            /** Reference Temperature C */
            reference_temperature_c?: number | null;
        };
        /** UMF */
        UMF: {
            /**
             * Status
             * @enum {string}
             */
            status: "AVAILABLE" | "UNAVAILABLE";
            /** Unavailable Reason */
            unavailable_reason: string | null;
            /** Values */
            values: {
                [key: string]: number;
            } | null;
        };
        /** ValidationContext */
        ValidationContext: {
            /** Body Analysis Id */
            body_analysis_id: string;
            /** Glaze Revision Id */
            glaze_revision_id: string;
            /** Firing Run Id */
            firing_run_id: string;
            /** Application Id */
            application_id: string;
            /** Analysis Report Id */
            analysis_report_id?: string | null;
            /** Chemistry Input Hash */
            chemistry_input_hash?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WindowCheck */
        WindowCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "AVAILABLE" | "UNAVAILABLE";
            /** Code */
            code: string;
            /** Source Ref */
            source_ref: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    simulation_thermal_comparison_api_v1_simulations_thermal_1d_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KilnThermalComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    simulation_thermal_1d_api_v1_simulations_thermal_1d_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KilnThermalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    simulation_capabilities_api_v1_simulations_capabilities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    simulation_chemistry_api_v1_simulations_chemistry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationChemistryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    calcite_explorer_api_v1_reactions_calcite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReactionExplorerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    openglaze_umf_reference_api_v1_references_openglaze_umf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenGlazeReferenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_with_openglaze_api_v1_references_openglaze_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChemistryComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_openglaze_comparison_api_v1_references_openglaze_replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonReplayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_openglaze_comparison_api_v1_references_openglaze_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonReplayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_openglaze_comparison_api_v1_references_openglaze_runs__comparison_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    temperature_comparison_api_v1_validation_temperature_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    outcome_indicators_api_v1_outcomes_assess_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validate_observed_outcomes_api_v1_validation_outcomes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_experiment_record_api_v1_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentRecordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_experiment_record_api_v1_experiments__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_observations_api_v1_experiments__record_id__observations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_experiment_observation_api_v1_experiments__record_id__observations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservedOutcome"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_experiment_measurements_api_v1_experiments__record_id__measurements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabMeasurementArchiveResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_experiment_measurement_api_v1_experiments__record_id__measurements_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabMeasurementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabMeasurementArchiveResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    save_validation_run_api_v1_validation_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentValidationArchiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_validation_run_api_v1_validation_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    materials_api_v1_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalogue"];
                };
            };
        };
    };
    library_api_v1_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
        };
    };
    material_analysis_api_v1_material_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_archive_recipes_api_v1_research_archive_recipes_get: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                page_size?: number;
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_archive_recipe_api_v1_research_archive_recipes__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReport"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
