/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Materials */
        get: operations["materials_api_v1_materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisReport */
        AnalysisReport: {
            /**
             * Schema Version
             * @default prototype-report/1
             * @constant
             */
            schema_version: "prototype-report/1";
            /** Report Id */
            report_id: string;
            request: components["schemas"]["AnalysisRequest"];
            chemistry: components["schemas"]["ChemistryResult"];
            /** Materials */
            materials: components["schemas"]["Material"][];
            /** Notices */
            notices: string[];
            /**
             * Persistence
             * @default NOT_STORED_EXPORT_TO_KEEP
             * @constant
             */
            persistence: "NOT_STORED_EXPORT_TO_KEEP";
        };
        /** AnalysisRequest */
        AnalysisRequest: {
            /** Recipe Name */
            recipe_name: string;
            /** Ingredients */
            ingredients: components["schemas"]["Ingredient"][];
            /**
             * Base Mass G
             * @default 100
             */
            base_mass_g: number;
            context?: components["schemas"]["FiringContext"];
        };
        /** Catalogue */
        Catalogue: {
            /** Materials */
            materials: components["schemas"]["Material"][];
            example: components["schemas"]["AnalysisRequest"];
            /** Notice */
            notice: string;
        };
        /** ChemistryResult */
        ChemistryResult: {
            /** Schema Version */
            schema_version: string;
            /** Engine Version */
            engine_version: string;
            /**
             * Evidence Kind
             * @constant
             */
            evidence_kind: "CALCULATED";
            /**
             * Method Kind
             * @constant
             */
            method_kind: "DETERMINISTIC";
            /** Qualifier */
            qualifier: string;
            /** Input Snapshot */
            input_snapshot: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Constant Set Id */
            constant_set_id: string;
            /** Constant Set Sha256 */
            constant_set_sha256: string;
            /** Umf Convention */
            umf_convention: string;
            /** Input Hash */
            input_hash: string;
            /** Normalized Ingredients */
            normalized_ingredients: components["schemas"]["NormalizedIngredient"][];
            /** Oxide Mass G */
            oxide_mass_g: {
                [key: string]: number;
            };
            /** Oxide Moles */
            oxide_moles: {
                [key: string]: number;
            };
            /** Oxide Mol Pct */
            oxide_mol_pct: {
                [key: string]: number;
            };
            /** Retained Oxide Wt Pct */
            retained_oxide_wt_pct: {
                [key: string]: number;
            };
            /** Loi Mass G */
            loi_mass_g: number;
            /** Retained Oxide Mass G */
            retained_oxide_mass_g: number;
            /** Total Dry Batch Mass G */
            total_dry_batch_mass_g: number;
            umf: components["schemas"]["UMF"];
            /** Flux Distribution */
            flux_distribution: {
                [key: string]: number;
            } | null;
            /** Ratios */
            ratios: {
                [key: string]: components["schemas"]["Ratio"];
            };
            /** Warnings */
            warnings: string[];
            predictions: components["schemas"]["Predictions"];
        };
        /** ErrorItem */
        ErrorItem: {
            /** Code */
            code: string;
            /** Path */
            path: string[];
            /** Message */
            message: string;
            /**
             * Severity
             * @default ERROR
             * @constant
             */
            severity: "ERROR";
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Errors */
            errors: components["schemas"]["ErrorItem"][];
        };
        /** FiringContext */
        FiringContext: {
            /**
             * Cone
             * @default UNKNOWN
             * @enum {string}
             */
            cone: "UNKNOWN" | "06" | "04" | "6" | "8" | "10";
            /** Temperature C */
            temperature_c?: number | null;
            /**
             * Atmosphere
             * @default UNKNOWN
             * @enum {string}
             */
            atmosphere: "UNKNOWN" | "OXIDATION" | "REDUCTION" | "OTHER";
            /**
             * Clay Body
             * @default
             */
            clay_body: string;
        };
        /** Ingredient */
        Ingredient: {
            /** Analysis Id */
            analysis_id: string;
            /** Amount */
            amount: number;
            /**
             * Role
             * @default BASE
             * @enum {string}
             */
            role: "BASE" | "ADDITION";
        };
        JsonValue: unknown;
        /** Material */
        Material: {
            /** Analysis Id */
            analysis_id: string;
            /** Name */
            name: string;
            /** Formula */
            formula: string;
            /** Version */
            version: string;
            /** Qualifier */
            qualifier: string;
            /** Basis */
            basis: string;
            /** Loi Pct */
            loi_pct: number;
            /** Oxides */
            oxides: {
                [key: string]: number;
            };
            /** Source Ref */
            source_ref: string;
            /** Source Url */
            source_url: string;
        };
        /** NormalizedIngredient */
        NormalizedIngredient: {
            /** Analysis Id */
            analysis_id: string;
            /** Amount */
            amount: number;
            /**
             * Role
             * @default BASE
             * @enum {string}
             */
            role: "BASE" | "ADDITION";
            /** Original Amount */
            original_amount: number;
            /** Percent Of Base */
            percent_of_base: number;
            /** Dry Mass G */
            dry_mass_g: number;
        };
        /** Predictions */
        Predictions: {
            /**
             * Status
             * @constant
             */
            status: "UNAVAILABLE";
            /** Reason */
            reason: string;
        };
        /** Ratio */
        Ratio: {
            /**
             * Status
             * @enum {string}
             */
            status: "AVAILABLE" | "UNAVAILABLE";
            /** Unavailable Reason */
            unavailable_reason: string | null;
            /** Value */
            value: number | null;
        };
        /** UMF */
        UMF: {
            /**
             * Status
             * @enum {string}
             */
            status: "AVAILABLE" | "UNAVAILABLE";
            /** Unavailable Reason */
            unavailable_reason: string | null;
            /** Values */
            values: {
                [key: string]: number;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    materials_api_v1_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalogue"];
                };
            };
        };
    };
    analyze_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReport"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
