'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '../lib/api';
import {type LibraryRecord,kinds,statuses,uses,fold,chemicalNames,firingLabel} from '../lib/library';
import CompositionChart from './composition-chart';
export default function MaterialLibrary({id}:{id?:string}){
 const [records,setRecords]=useState<LibraryRecord[]>([]),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 const [q,setQ]=useState(''),[kind,setKind]=useState(''),[chemicalQ,setChemicalQ]=useState(''),[selected,setSelected]=useState<string[]>([]),[sort,setSort]=useState('name'),[oxide,setOxide]=useState('SiO2'),[page,setPage]=useState(1);
 useEffect(()=>{const c=new AbortController();api<{records:LibraryRecord[]}>('library',{signal:c.signal}).then(r=>{setRecords(r.records);setLoaded(true);}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[]);
 const allOxides=Array.from(new Set([...Object.keys(chemicalNames),...records.flatMap(r=>Object.keys(r.oxides))])).sort();
 const filtered=records.filter(r=>(!kind||r.kind===kind)&&fold(`${r.name} ${r.brand} ${r.formula??''}`).includes(fold(q))&&selected.every(o=>(r.oxides[o]??0)>0)).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'tr'):sort==='reverse'?b.name.localeCompare(a.name,'tr'):(b.oxides[oxide]??-1)-(a.oxides[oxide]??-1)||a.name.localeCompare(b.name,'tr'));
 const pages=Math.max(1,Math.ceil(filtered.length/12));const current=Math.min(page,pages);
 if(error)return <p role="alert">Kütüphane yüklenemedi: {error}</p>;
 if(!loaded)return <p role="status">Kaynaklı kayıtlar yükleniyor…</p>;
 if(id){const r=records.find(r=>r.id===id);if(!r)return <section><h1>Kayıt bulunamadı</h1><Link href="/materials">Kütüphaneye dön</Link></section>;
 return <article className="library-detail"><Link href="/materials">← Malzeme kütüphanesi</Link><p className="eyebrow">{kinds[r.kind]} · {r.brand}</p><h1>{r.name}</h1><span className="tag">{statuses[r.status]}</span><p>{r.note}</p><div className="library-detail-grid"><section className="card"><h2>Kimyasal bileşim</h2>{r.formula&&<p>{r.formula}</p>}<CompositionChart oxides={r.oxides} basis={r.basis}/><p>LOI: {r.loi===null?'Bilinmiyor':r.loi.toLocaleString('tr-TR')+' %'}</p><p>{r.engine_eligible?'Teorik analiz mevcut reçete motorunda kullanılabilir.':'Hesap motoruna kabul edilmedi. Grafik, analiz onayı değildir.'}</p></section><section className="card"><h2>Pişirim ve kullanım</h2><p>{firingLabel(r)}</p>{r.windows.filter(w=>w.stage==='BISQUE').map((w,i)=><p key={i}>Bisküvi: {w.min_c}–{w.max_c} °C</p>)}<p>{r.uses.length?r.uses.map(u=>uses[u]??u).join(' · '):'Kaynaklı kullanım alanı henüz kayıtlı değil.'}</p><p>Aralıklar bildirilen ürün bilgileridir; sır–bünye uyumu veya başarı garantisi değildir. Atmosfer, hız ve bekleme koşulları eksik olabilir.</p><details><summary>Tarihçe ve özellikler neden eksik olabilir?</summary><p>Doğrulanmış tarihsel kaynak ve ürün özelinde kanıt olmadan ilk kullanım, artistik üstünlük veya kesin yüzey etkisi eklenmez.</p></details></section></div><section className="card"><h2>Kaynak ve analiz sürümü</h2><p>{r.source_name}</p><a href={r.source_url} target="_blank" rel="noreferrer">Kaynağı incele ↗</a><p>Sürüm: {r.version} · İnceleme: {r.review_date??'Teorik sabit seti'} · Lisans: {r.license}</p><p>Ürün dizinleri yeniden yayınlama/eğitim izni verilmiş veri setleri değildir. Bu ekran yerel araştırma içindir.</p>{r.flags.length>0&&<details><summary>İnceleme notları ({r.flags.length})</summary><ul>{r.flags.map(f=><li key={f}>{f}</li>)}</ul></details>}</section></article>}
 return <section className="library-browser"><div className="library-intro"><h2>Malzemeyi bul, kaynağını incele.</h2><p>{records.length} kayıt · {records.filter(r=>r.engine_eligible).length} teorik hesap girdisi. Diğerleri araştırma dizini veya inceleme bekleyen analizdir.</p></div><div className="library-layout"><aside className="card library-filters"><label className="field">Malzeme veya marka ara<input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Stoneware, kaolinit, Akasya…"/></label><label className="field">Malzeme türü<select value={kind} onChange={e=>{setKind(e.target.value);setPage(1)}}><option value="">Tüm türler</option>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field">Sıralama<select value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="name">İsim A–Z</option><option value="reverse">İsim Z–A</option><option value="oxide">Oksit yüzdesi · yüksekten düşüğe</option></select></label>{sort==='oxide'&&<label className="field">Sıralanacak oksit<select value={oxide} onChange={e=>{setOxide(e.target.value);setPage(1)}}>{allOxides.map(o=><option key={o}>{o}</option>)}</select></label>}
 <fieldset><legend>Kimyasal bileşenler</legend><label className="field">Oksit ara<input value={chemicalQ} onChange={e=>setChemicalQ(e.target.value)} placeholder="SiO2 veya silisyum"/></label><p className="helper">Seçilenlerin tümünü pozitif raporlayan kayıtlar. Analizi eksik ürünler eşleşmeyebilir; bu, oksidin yokluğu anlamına gelmez.</p><div className="oxide-checks">{allOxides.filter(o=>fold(o+' '+(chemicalNames[o]??'')).includes(fold(chemicalQ))).map(o=><label key={o}><input type="checkbox" checked={selected.includes(o)} onChange={e=>{setSelected(s=>e.target.checked?[...s,o]:s.filter(x=>x!==o));setPage(1)}}/>{o} <small>{chemicalNames[o]}</small></label>)}</div></fieldset><p>{selected.length?`Seçili: ${selected.join(', ')}`:'Oksit filtresi yok'}</p><button type="button" onClick={()=>{setQ('');setKind('');setSelected([]);setChemicalQ('');setPage(1)}}>Filtreleri temizle</button><p className="helper">Farklı analiz bazlarını yalnızca yüzdelere göre bilimsel olarak sıralamak uygun değildir; bu bir katalog sıralamasıdır.</p></aside><div><p role="status">{filtered.length} eşleşme · Sayfa {current}/{pages}</p><div className="library-cards">{filtered.slice((current-1)*12,current*12).map(r=><article className="card" key={r.id}><span className="tag">{kinds[r.kind]}</span><h3><Link href={`/materials/${encodeURIComponent(r.id)}`}>{r.name}</Link></h3><p>{r.brand}</p><p className="helper">{firingLabel(r)}</p><small>{statuses[r.status]}</small><p className="helper">{Object.keys(r.oxides).length?Object.keys(r.oxides).join(' · '):'Kimyasal analiz kayıtlı değil'}</p><Link href={`/materials/${encodeURIComponent(r.id)}`}>Bileşim ve kaynak →</Link></article>)}</div>{!filtered.length&&<p>Bu filtrelere uyan kayıt yok. Filtreleri azaltabilir veya farklı bir ad arayabilirsin.</p>}<nav className="library-pagination" aria-label="Kütüphane sayfaları"><button type="button" disabled={current===1} onClick={()=>setPage(current-1)}>← Önceki</button><span>{current} / {pages}</span><button type="button" disabled={current===pages} onClick={()=>setPage(current+1)}>Sonraki →</button></nav></div></div></section>;
}
