'use client';
import {useEffect,useState} from 'react';
import {api} from '../lib/api';
type Recipe={id:number;name:string;subtype:string;cone:string;surface:string;ingredients_count:number};
type SearchResult={total:number;page:number;page_size:number;category:string;items:Recipe[];scope:string;engine_eligible:boolean};
type Detail={source_id:number;source_line:number;record:Record<string,unknown>;archive_sha256:string;parser_version:string;status:string;engine_eligible:boolean};
type Ingredient={Name?:string;ID?:number;Percentage?:number;Additional?:boolean};
type Analysis=Record<string,number>;
function DetailPanel({detail,onClose}:{detail:Detail;onClose:()=>void}){
 const r=detail.record, ingredients=Array.isArray(r.Ingredients)?r.Ingredients as Ingredient[]:[], analysis=(r['Percent Analysis']&&typeof r['Percent Analysis']==='object'?r['Percent Analysis'] as Analysis:{});
 const oxides=Object.entries(analysis).filter(([,v])=>typeof v==='number').sort((a,b)=>b[1]-a[1]);
 return <div className="archive-detail"><div className="archive-detail-head"><div><p className="eyebrow">ARŞİV KAYDI · ID {detail.source_id}</p><h3>{String(r.Name??'İsimsiz kayıt')}</h3></div><button type="button" onClick={onClose}>Kapat</button></div><p className="helper">Kaynak satırı {detail.source_line} · Parser {detail.parser_version} · <strong>QUARANTINE</strong></p><div className="archive-detail-grid"><section><h4>Reçete bileşenleri</h4>{ingredients.length?<ul className="archive-ingredients">{ingredients.map((i,n)=><li key={`${i.ID}-${n}`}><span>{i.Name??`Malzeme ID ${i.ID??'?'}`}</span><strong>{typeof i.Percentage==='number'?`${i.Percentage} %`:'miktar belirtilmemiş'}{i.Additional?' · ilave':''}</strong></li>)}</ul>:<p className="helper">Bileşen satırı bulunmuyor.</p>}</section><section><h4>Raporlanan oksit analizi</h4>{oxides.length?<ul className="archive-oxides">{oxides.map(([name,value])=><li key={name}><span>{name}</span><strong>{value} %</strong></li>)}</ul>:<p className="helper">Oksit analizi bulunmuyor.</p>}<p className="helper">Bu yüzdeler UMF hesabı değildir; analiz bazı ve doğrulama durumu ayrıca incelenmelidir.</p></section></div><details><summary>Özgün alanları göster</summary><pre>{JSON.stringify(r,null,2)}</pre></details></div>;
}
export default function ResearchArchive(){
 const [q,setQ]=useState(''),[category,setCategory]=useState(''),[page,setPage]=useState(1),[data,setData]=useState<SearchResult|null>(null),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();api<SearchResult>(`research/archive/recipes?q=${encodeURIComponent(q)}&page=${page}&page_size=12&category=${category}`,{signal:c.signal}).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[q,page,category]);
 const pages=data?Math.max(1,Math.ceil(data.total/data.page_size)):1;
 return <section className="card research-archive"><div className="research-heading"><div><p className="eyebrow">YEREL ARAŞTIRMA ARŞİVİ</p><h2>Geniş reçete havuzu</h2><p>Arşiv kayıtları kaynak incelemesi içindir; otomatik olarak kimya motoruna aktarılmaz.</p></div><span className="tag">QUARANTINE · {data?.total??'…'} eşleşme</span></div><label className="field">Reçete ara<input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Tenmoku, porcelain, celadon…"/></label>{error&&<p role="alert">Arşiv yüklenemedi: {error}</p>}{data&&<><p className="helper">{data.total.toLocaleString('tr-TR')} kayıt · sayfa {page}/{pages} · snapshot korunuyor</p><div className="archive-list">{data.items.map(r=><article key={r.id}><div><strong>{r.name}</strong><small>{r.subtype||'Tür belirtilmemiş'} · {r.cone||'Cone belirtilmemiş'} · {r.surface||'Yüzey belirtilmemiş'}</small></div><button type="button" onClick={()=>api<Detail>(`research/archive/recipes/${r.id}`).then(setDetail)}>Kaydı incele</button></article>)}</div><nav className="library-pagination"><button type="button" disabled={page===1} onClick={()=>setPage(page-1)}>← Önceki</button><span>{page} / {pages}</span><button type="button" disabled={page===pages} onClick={()=>setPage(page+1)}>Sonraki →</button></nav></>}{detail&&<DetailPanel detail={detail} onClose={()=>setDetail(null)}/>}</section>
}
